"""Generate the PathSense idea/results PPT (16:9) with real metrics.

Parses metrics_report.md (auto-generated by scripts/run_all_scenarios.py) for
per-scenario results and pairs each with its scenario plot PNG.

Usage:
    venv/Scripts/python.exe scripts/make_ppt.py
Output:
    pathsense_ppt.pptx
"""
import os
import re
import sys

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.util import Inches, Pt

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPORT = os.path.join(ROOT, "metrics_report.md")
OUT = os.path.join(ROOT, "pathsense_ppt.pptx")

NAVY = RGBColor(0x0D, 0x47, 0xA1)
DARK = RGBColor(0x26, 0x32, 0x38)
GREEN = RGBColor(0x1B, 0x5E, 0x20)
RED = RGBColor(0xC6, 0x28, 0x28)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
BLUE_BG = RGBColor(0xE3, 0xF2, 0xFD)
GREEN_BG = RGBColor(0xE8, 0xF5, 0xE9)

SLIDE_W, SLIDE_H = Inches(13.333), Inches(7.5)

# metrics_report.md scenario name -> (ppt title, plot png, caption)
SCENARIOS = [
    ("Static Obstacle", "scenario_static_obstacle.png",
     "A* reroutes around a blocked lane; DWA keeps a safe margin."),
    ("Crossing Animal", "scenario_crossing_animal.png",
     "Sudden goat crossing: time-aware DWA predicts motion and swerves within dynamic limits."),
    ("Multi Animal", "scenario_multi_animal.png",
     "Simultaneous dynamic obstacles handled with zero emergency stops."),
    ("Indian Road", "scenario_indian_road.png",
     "Encroaching carts, wrong-side traffic and potholes on a single route."),
    ("City Roads", "scenario_city_roads.png",
     "Dense urban traffic; emergency stops used, zero collisions."),
    ("Sensor Noise", "scenario_sensor_noise.png",
     "Noisy detections still yield a stable, collision-free path."),
    ("Occluded Siren", "scenario_occluded_siren.png",
     "Acoustic attention: the vehicle hears the siren it cannot see and creeps cautiously."),
]

# Key metrics highlighted per scenario (substring match on report keys).
HIGHLIGHTS = {
    "Static Obstacle": ["Min Clearance", "Path Efficiency"],
    "Crossing Animal": ["Min Ttc S", "Path Efficiency", "Rejoin"],
    "Multi Animal": ["Min Clearance", "Emergency Stops"],
    "Indian Road": ["Path Efficiency", "Min Clearance"],
    "City Roads": ["Emergency Stops", "Path Efficiency"],
    "Sensor Noise": ["Min Clearance", "Path Efficiency"],
    "Occluded Siren": ["Max Hold Speed", "Post Siren", "Emergency Stops"],
}


def parse_report():
    """Return {scenario_name: {metric: formatted_string, 'status': ...}}."""
    if not os.path.exists(REPORT):
        print(f"WARNING: {REPORT} not found - slides will have no metrics.")
        return {}
    text = open(REPORT, encoding="utf-8", errors="replace").read()
    sections = re.split(r"^### ", text, flags=re.M)[1:]
    data = {}
    for sec in sections:
        lines = sec.strip().splitlines()
        name = lines[0].strip()
        metrics = {}
        for ln in lines[1:]:
            m = re.match(r"- \*\*(.+?):\*\* (.+)", ln.strip())
            if m:
                metrics[m.group(1)] = m.group(2)
        data[name] = metrics
    return data


def add_bg(slide, color):
    slide.background.fill.solid()
    slide.background.fill.fore_color.rgb = color


def add_title(slide, text, color=NAVY, size=32):
    box = slide.shapes.add_textbox(Inches(0.6), Inches(0.35),
                                   SLIDE_W - Inches(1.2), Inches(1.0))
    tf = box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = Pt(size)
    p.font.bold = True
    p.font.color.rgb = color


def add_bullets(slide, items, left, top, width, height, size=16):
    box = slide.shapes.add_textbox(left, top, width, height)
    tf = box.text_frame
    tf.word_wrap = True
    for i, (txt, lvl) in enumerate(items):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.text = ("• " if lvl == 0 else "– ") + txt if lvl >= 0 else txt
        p.level = max(lvl, 0)
        p.font.size = Pt(size if lvl == 0 else size - 2)
        p.font.color.rgb = DARK
        p.space_after = Pt(8)


def add_footer(slide, text):
    box = slide.shapes.add_textbox(Inches(0.6), SLIDE_H - Inches(0.55),
                                   SLIDE_W - Inches(1.2), Inches(0.4))
    p = box.text_frame.paragraphs[0]
    p.text = text
    p.font.size = Pt(11)
    p.font.color.rgb = RGBColor(0x90, 0xA4, 0xAE)


def slide_scenario(prs, title, png, caption, metrics, highlights):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    add_bg(slide, WHITE)
    add_title(slide, title)

    img = os.path.join(ROOT, png)
    if os.path.exists(img):
        # plot PNGs are 10x8 in aspect; fit into the left 60% of the slide
        slide.shapes.add_picture(img, Inches(0.6), Inches(1.5),
                                 width=Inches(7.4))
    else:
        add_bullets(slide, [(f"[missing plot: {png}]", 0)],
                    Inches(0.6), Inches(2.0), Inches(7.0), Inches(3.0))

    # Right panel: caption + key metrics
    x = Inches(8.3)
    cap = slide.shapes.add_textbox(x, Inches(1.5), Inches(4.4), Inches(1.2))
    cap.text_frame.word_wrap = True
    p = cap.text_frame.paragraphs[0]
    p.text = caption
    p.font.size = Pt(14)
    p.font.italic = True
    p.font.color.rgb = DARK

    y = Inches(2.9)
    status = metrics.get("Status", "")
    chip = slide.shapes.add_textbox(x, y, Inches(4.4), Inches(0.5))
    cp = chip.text_frame.paragraphs[0]
    cp.text = f"Status: {status or 'n/a'}"
    cp.font.size = Pt(16)
    cp.font.bold = True
    cp.font.color.rgb = GREEN if status.upper() == "PASS" else RED
    y += Inches(0.7)

    for key in highlights:
        for mk, mv in metrics.items():
            if key.lower() in mk.lower():
                box = slide.shapes.add_textbox(x, y, Inches(4.4), Inches(0.45))
                bp = box.text_frame.paragraphs[0]
                bp.text = f"{mk.replace('_', ' ')}:  {mv}"
                bp.font.size = Pt(14)
                bp.font.color.rgb = DARK
                y += Inches(0.5)
                break
    add_footer(slide, "PathSense · SIH26037")
    return slide


def main():
    data = parse_report()
    prs = Presentation()
    prs.slide_width, prs.slide_height = SLIDE_W, SLIDE_H

    # --- 1. Title -----------------------------------------------------------
    s = prs.slides.add_slide(prs.slide_layouts[6])
    add_bg(s, NAVY)
    box = s.shapes.add_textbox(Inches(0.8), Inches(2.2),
                               SLIDE_W - Inches(1.6), Inches(2.6))
    tf = box.text_frame
    tf.word_wrap = True
    for i, (txt, size) in enumerate([
            ("PathSense", 54),
            ("Adaptive Path Planning & Collision Avoidance "
             "for Autonomous Vehicles on Unstructured Indian Roads", 24),
            ("Smart India Hackathon 2026 · Problem Statement SIH26037", 16)]):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.text = txt
        p.font.size = Pt(size)
        p.font.bold = (i == 0)
        p.font.color.rgb = WHITE if i < 2 else RGBColor(0xBB, 0xDE, 0xFB)
        p.space_after = Pt(14)

    # --- 2. Problem -----------------------------------------------------------
    s = prs.slides.add_slide(prs.slide_layouts[6])
    add_bg(s, WHITE)
    add_title(s, "The Problem: Roads That Don't Follow the Textbook")
    add_bullets(s, [
        ("Indian roads are unstructured: lanes, rules and geometry are "
         "negotiated in real time.", 0),
        ("Cows, goats and pedestrians cross anywhere, anytime.", 0),
        ("Carts, parked vehicles and potholes shrink the drivable corridor.", 0),
        ("Wrong-side traffic and occluded bends hide threats until the "
         "last second.", 0),
        ("", 0),
        ("Standard AD planners assume lane markings, structured traffic and "
         "predictable agents - they fail here.", 0),
        ("Sound often arrives before sight: horns and sirens around "
         "occlusions are invisible to cameras.", 0),
    ], Inches(0.8), Inches(1.7), Inches(11.7), Inches(4.8), size=20)
    add_footer(s, "PathSense · SIH26037")

    # --- 3. Solution / architecture -------------------------------------------
    s = prs.slides.add_slide(prs.slide_layouts[6])
    add_bg(s, BLUE_BG)
    add_title(s, "Our Solution: A Full Autonomy Stack Built for Chaos")
    add_bullets(s, [
        ("Perception", 0),
        ("Ground-truth / noisy sensor simulation + synthetic camera vision "
         "pipeline (Sprint 2+)", 1),
        ("Acoustic attention: horn/siren cues with direction-of-arrival "
         "(occluded threats)", 1),
        ("Mapping", 0),
        ("Local costmap with inflation on a road-network prior", 1),
        ("Global planning", 0),
        ("A* on the costmap with dynamic replanning when the route blocks", 1),
        ("Local planning & collision avoidance", 0),
        ("Time-aware DWA: predicts dynamic obstacles forward in time, "
         "respects steering/braking limits", 1),
        ("OBB (oriented bounding box) collision geometry - no inflated-circle "
         "cheats", 1),
        ("Control & safety", 0),
        ("Pure Pursuit + kinematic bicycle model", 1),
        ("Independent envelope safety monitor: physical-limit enforcement as "
         "a last line of defence", 1),
    ], Inches(0.8), Inches(1.6), Inches(11.7), Inches(5.2), size=17)
    add_footer(s, "PathSense · SIH26037")

    # --- 4. Innovation / USP ----------------------------------------------------
    s = prs.slides.add_slide(prs.slide_layouts[6])
    add_bg(s, WHITE)
    add_title(s, "What Makes This Different")
    add_bullets(s, [
        ("Time-aware obstacle prediction - DWA scores trajectories against "
         "where animals WILL be, not where they are.", 0),
        ("Audio-visual fusion - a mic-array 'acoustic attention' module "
         "hears horns/sirens around occlusions and couples them to speed "
         "capping (creep-and-yield).", 0),
        ("Independent safety envelope - a monitor outside the planner "
         "physically vetoes impossible commands.", 0),
        ("Honest metrics - collision counts, TTC, path efficiency, jerk and "
         "planning latency auto-reported for every scenario run.", 0),
        ("Deterministic, testable pipeline - 7 scripted Indian-road "
         "scenarios, one command, reproducible results.", 0),
    ], Inches(0.8), Inches(1.8), Inches(11.7), Inches(4.6), size=19)
    add_footer(s, "PathSense · SIH26037")

    # --- 5. Results summary -------------------------------------------------------
    s = prs.slides.add_slide(prs.slide_layouts[6])
    add_bg(s, GREEN_BG)
    add_title(s, "Results: 7 / 7 Scenarios PASS, Zero Collisions", GREEN)
    rows = [("Scenario", "Status", "Path Eff.", "Min Clearance",
             "E-Stops", "Min TTC")]
    for name, _, _ in SCENARIOS:
        m = data.get(name, {})
        eff = next((m[k] for k in m if "efficiency" in k.lower()), "-")
        rows.append((
            name,
            m.get("Status", "-"),
            eff,
            next((m[k] for k in m if "clearance" in k.lower()), "-"),
            m.get("Emergency Stops", "-"),
            next((m[k] for k in m if "min ttc" in k.lower()
                  and "overall" not in k.lower()), "-"),
        ))
    n_rows = len(rows)
    tbl = s.shapes.add_table(n_rows, 6, Inches(0.6), Inches(1.6),
                             Inches(12.1), Inches(0.5) * n_rows).table
    for c, w in enumerate([Inches(3.0), Inches(1.6), Inches(2.0),
                           Inches(2.2), Inches(1.6), Inches(1.7)]):
        tbl.columns[c].width = w
    for r, row in enumerate(rows):
        for c, val in enumerate(row):
            cell = tbl.cell(r, c)
            cell.text = str(val)
            para = cell.text_frame.paragraphs[0]
            para.font.size = Pt(13 if r else 14)
            para.font.bold = (r == 0 or c == 1)
            if r and c == 1:
                para.font.color.rgb = (GREEN if str(val).upper() == "PASS"
                                       else RED)
    add_footer(s, "Full details: metrics_report.md (auto-generated)")

    # --- 6-12. One slide per scenario ---------------------------------------------
    for name, png, caption in SCENARIOS:
        slide_scenario(prs, name, png, caption, data.get(name, {}),
                       HIGHLIGHTS.get(name, []))

    # --- 13. Limitations -------------------------------------------------------------
    s = prs.slides.add_slide(prs.slide_layouts[6])
    add_bg(s, WHITE)
    add_title(s, "Honest Limitations")
    add_bullets(s, [
        ("Vision pipeline uses a synthetic camera model - no trained "
         "detector weights yet; detection is geometry-driven.", 0),
        ("Acoustic module runs on synthetic event injection, not live mic "
         "hardware.", 0),
        ("City-roads scenario needs 5 emergency stops - comfort tuning is "
         "open.", 0),
        ("Single ego vehicle; no multi-agent negotiation yet.", 0),
        ("Simulation-first: hardware port is a stretch goal.", 0),
    ], Inches(0.8), Inches(1.8), Inches(11.7), Inches(4.0), size=19)
    add_footer(s, "PathSense · SIH26037")

    # --- 14. Roadmap -------------------------------------------------------------------
    s = prs.slides.add_slide(prs.slide_layouts[6])
    add_bg(s, BLUE_BG)
    add_title(s, "Road to Submission (30 Sep)")
    add_bullets(s, [
        ("Sprint 3 (23-27 Sep): full-suite hardening, dashboard polish, "
         "stress tests.", 0),
        ("Sprint 4 (28-30 Sep): demo video, final PPT with these results, "
         "dry runs.", 0),
        ("Stretch: small-scale hardware rig + live audio capture.", 0),
    ], Inches(0.8), Inches(1.9), Inches(11.7), Inches(3.0), size=20)
    add_footer(s, "PathSense · SIH26037")

    prs.save(OUT)
    print(f"[PPT] Saved {OUT} ({len(prs.slides._sldIdLst)} slides)")


if __name__ == "__main__":
    main()
